version: 0.2
phases:    
  install:
    runtime-versions:
      nodejs: 10      
    commands:            
      - 'touch .npmignore'            
      - 'npm install -g gatsby'    
  pre_build:
    commands:
      - echo "pre_build step"
      - cd ./wildaid-sandbox
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete "./public/" "s3://www.bethepride.com" --acl "public-read"
      - echo "post_build step"